---
# tasks file for iscsi

# Copyright (C) 2020 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: include centos_7.yml, when CentOS 7
  include: centos_7.yml
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'
  tags: common

